# Setup-AutoUpdate.ps1
# A colleague runs this ONCE (via Setup-AutoUpdate.bat) from the network share.
# It registers a per-user logon task that mirrors the shared bundle into the
# local ApplicationPlugins folder, then runs it immediately. No admin needed.
#
# The share path is auto-detected as the folder this script runs from, so there
# is nothing to edit — just run it from the share. Override with -SharePath.

param(
    [string]$SharePath = (Split-Path -Parent $MyInvocation.MyCommand.Path)
)

$ErrorActionPreference = "Stop"
$bundleName  = "OALayerManager.bundle"
$shareBundle = Join-Path $SharePath $bundleName
$localBundle = Join-Path $env:APPDATA "Autodesk\ApplicationPlugins\$bundleName"

Write-Host "=========================================="
Write-Host " OA Layer Manager - Enable Auto-Update"
Write-Host "=========================================="

if (-not (Test-Path $shareBundle)) {
    Write-Host "ERROR: Could not find $bundleName on the share:" -ForegroundColor Red
    Write-Host "  $shareBundle"
    Write-Host "Run this script from the shared plugin folder, or pass -SharePath."
    exit 1
}

# 1. Write the small updater script to the user's local profile.
$updaterDir  = Join-Path $env:LOCALAPPDATA "OALayerManager"
New-Item -ItemType Directory -Force -Path $updaterDir | Out-Null
$updaterPath = Join-Path $updaterDir "Update-OALayerManager.ps1"

@"
# Auto-generated by Setup-AutoUpdate.ps1 - mirrors the shared bundle locally.
`$share = '$shareBundle'
`$local = '$localBundle'
if (Test-Path `$share) {
    # /MIR brings new buttons, code changes, and removes deleted files.
    # Skips locked files gracefully if AutoCAD happens to be open.
    robocopy `$share `$local /MIR /R:1 /W:1 /NFL /NDL /NJH /NJS /NP | Out-Null
}
"@ | Set-Content -Path $updaterPath -Encoding UTF8

# 2. Run at every logon via a Startup-folder shortcut (no admin required).
$startup = [Environment]::GetFolderPath("Startup")
$lnkPath = Join-Path $startup "OA Layer Manager Update.lnk"
$ws  = New-Object -ComObject WScript.Shell
$lnk = $ws.CreateShortcut($lnkPath)
$lnk.TargetPath  = "powershell.exe"
$lnk.Arguments   = "-NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File `"$updaterPath`""
$lnk.Description  = "Keeps the OA Layer Manager AutoCAD plugin up to date."
$lnk.Save()

# 3. Run it once now so the plugin is installed/updated immediately.
& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $updaterPath

Write-Host ""
Write-Host "Done!" -ForegroundColor Green
Write-Host " - Plugin synced to: $localBundle"
Write-Host " - It will refresh automatically every time you log in."
Write-Host " - Restart AutoCAD to load the latest version."
